version: '3.9'

services:
  mongo:
    image: mongo:6.0  # Usar MongoDB 6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mc05071995..
    ports:
      - "27017:27017"
    volumes:
      - MongoData:/data/db  # Montar el volumen
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js  # Añadir script de inicialización
    restart: always

  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Mc05071995..
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    restart: always

# Definición de volúmenes persistentes
volumes:
  MongoData: